### ISSUE TITLE
Quotation Mark change.

### ISSUE THREAD

**Issue by frisina** [learn-co-curriculum/cli-essentials-bash-programming#4]
`$ echo "Hi world!" `
This surfaces an error in the terminal:

` -bash: !": event not found. `

Should be changed to: 

`$ echo 'Hi world!'`

**Comment by sgharms** [comment]
Changed our approach slightly, but this is a good idea. It's that pesky `!` trying to do history lookups.

Fixed in https://github.com/learn-co-curriculum/cli-essentials-bash-programming/commit/b366f2efe82d86243419c60335cfe33dd00cd660
