### ISSUE TITLE
Link appears to be expired

### ISSUE THREAD

**Issue by Shane-Black** [learn-co-curriculum/cli-essentials-bash-programming#9]
http://www.mactricksandtips.com/2012/07/using-the-terminal-command-cat-to-view-the-contents-of-files.html appears to be an expired domain that is parked by GoDaddy... i.e. no content.

**Comment by ihollander** [comment]
Fixed by https://github.com/learn-co-curriculum/cli-essentials-bash-programming/commit/62ddf8dd4c2a9c726f822fe018e0c005ceb0543c
